apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: carol-johnson
  description: DevOps Engineer specializing in Kubernetes and CI/CD
  annotations:
    backstage.io/managed-by-location: url:https://github.com/brunokino/backstage-entities-example/blob/main/org/users/carol-johnson.yaml
  links:
    - url: https://github.com/carol-johnson
      title: GitHub Profile
      icon: github
    - url: https://www.linkedin.com/in/carol-johnson
      title: LinkedIn Profile
      icon: linkedin
spec:
  profile:
    displayName: Carol Johnson
    email: carol.johnson@kinoshita-labs.com
    picture: https://avatars.dicebear.com/api/avataaars/carol-johnson.svg
  memberOf:
    - platform-team

